services:
  postgres:
    image: postgres:16
    container_name: homeworkdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5433:5432"
    networks:
      - homework-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: homeworkdatabase
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - homeworknetwork

volumes:
  pgadmin_data:
